//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Tes
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Позиция.
    /// </summary>
    // *** Start programmer edit section *** (Позиция CustomAttributes)

    // *** End programmer edit section *** (Позиция CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПозицияE", new string[] {
            "Колич as \'Количество\'"})]
    public class Позиция : ICSSoft.STORMNET.DataObject
    {
        
        private int fКолич;
        
        private IIS.Tes.Продажа fПродажа;
        
        // *** Start programmer edit section *** (Позиция CustomMembers)

        // *** End programmer edit section *** (Позиция CustomMembers)

        
        /// <summary>
        /// Колич.
        /// </summary>
        // *** Start programmer edit section *** (Позиция.Колич CustomAttributes)

        // *** End programmer edit section *** (Позиция.Колич CustomAttributes)
        public virtual int Колич
        {
            get
            {
                // *** Start programmer edit section *** (Позиция.Колич Get start)

                // *** End programmer edit section *** (Позиция.Колич Get start)
                int result = this.fКолич;
                // *** Start programmer edit section *** (Позиция.Колич Get end)

                // *** End programmer edit section *** (Позиция.Колич Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Позиция.Колич Set start)

                // *** End programmer edit section *** (Позиция.Колич Set start)
                this.fКолич = value;
                // *** Start programmer edit section *** (Позиция.Колич Set end)

                // *** End programmer edit section *** (Позиция.Колич Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Tes.Продажа.
        /// </summary>
        // *** Start programmer edit section *** (Позиция.Продажа CustomAttributes)

        // *** End programmer edit section *** (Позиция.Продажа CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Tes.Продажа Продажа
        {
            get
            {
                // *** Start programmer edit section *** (Позиция.Продажа Get start)

                // *** End programmer edit section *** (Позиция.Продажа Get start)
                IIS.Tes.Продажа result = this.fПродажа;
                // *** Start programmer edit section *** (Позиция.Продажа Get end)

                // *** End programmer edit section *** (Позиция.Продажа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Позиция.Продажа Set start)

                // *** End programmer edit section *** (Позиция.Продажа Set start)
                this.fПродажа = value;
                // *** Start programmer edit section *** (Позиция.Продажа Set end)

                // *** End programmer edit section *** (Позиция.Продажа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПозицияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПозицияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПозицияE", typeof(IIS.Tes.Позиция));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Позиция.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfПозиция CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfПозиция CustomAttributes)
    public class DetailArrayOfПозиция : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Tes.DetailArrayOfПозиция members)

        // *** End programmer edit section *** (IIS.Tes.DetailArrayOfПозиция members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Позиция by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Позиция.
        /// </summary>
        public DetailArrayOfПозиция(IIS.Tes.Продажа fПродажа) : 
                base(typeof(Позиция), ((ICSSoft.STORMNET.DataObject)(fПродажа)))
        {
        }
        
        public IIS.Tes.Позиция this[int index]
        {
            get
            {
                return ((IIS.Tes.Позиция)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Tes.Позиция dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
