//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Tes
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ТипПродажи.
    /// </summary>
    // *** Start programmer edit section *** (ТипПродажи CustomAttributes)

    // *** End programmer edit section *** (ТипПродажи CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТипПродажиE", new string[] {
            "Название as \'Название\'"})]
    [View("ТипПродажиL", new string[] {
            "Название as \'Название\'"})]
    public class ТипПродажи : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        // *** Start programmer edit section *** (ТипПродажи CustomMembers)

        // *** End programmer edit section *** (ТипПродажи CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (ТипПродажи.Название CustomAttributes)

        // *** End programmer edit section *** (ТипПродажи.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (ТипПродажи.Название Get start)

                // *** End programmer edit section *** (ТипПродажи.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (ТипПродажи.Название Get end)

                // *** End programmer edit section *** (ТипПродажи.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТипПродажи.Название Set start)

                // *** End programmer edit section *** (ТипПродажи.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (ТипПродажи.Название Set end)

                // *** End programmer edit section *** (ТипПродажи.Название Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТипПродажиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТипПродажиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТипПродажиE", typeof(IIS.Tes.ТипПродажи));
                }
            }
            
            /// <summary>
            /// "ТипПродажиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТипПродажиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТипПродажиL", typeof(IIS.Tes.ТипПродажи));
                }
            }
        }
    }
}
